kind: pipeline
type: docker
name: demonstrator

steps:
- name: codacy
  image: plugins/codacy
  settings:
    token:
      from_secret: codacy_token
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    repo: scratchitea3/demonstrator
    tags:
      - latest
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: build-automation
    when:
      status: [ success, failure ]
