kind: pipeline
type: docker
name: arm

platform:
  arch: arm
  os: linux

steps:
- name: codacy
  image: plugins/codacy
  settings:
    token:
      from_secret: codacy_token

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    repo: scratchitea3/demonstrator
    tags:
      - linux-arm

---
kind: pipeline
type: docker
name: x86

platform:
  arch: amd64
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    repo: scratchitea3/demonstrator
    tags:
      - linux-amd64

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    target: scratchitea3/demonstrator
    template: scratchitea3/demonstrator:OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm

depends_on:
- arm
- x86

---
kind: pipeline
type: docker
name: notification

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: build-automation
    when:
      status: [ success, failure ]

depends_on:
- manifest
