kind: pipeline
type: docker
name: demonstrator

platform:
  os: linux
  arch: arm
  
steps:
- name: codacy
  image: plugins/codacy
  settings:
    token:
      from_secret: codacy_token
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: build-automation
    when:
      status: [ success, failure ]
